import { useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import { AmbassadorDialog } from '../components/AmbassadorDialog';
import { DirectoryOperationList } from '../components/DirectoryOperationList';
import { adminFulfilmentCommands } from '../data/adminFulfilmentCommands';
import { useFulfilment } from '../hooks/useFulfilment';
import { useOperationsState } from '../hooks/useOperations';
import type { AmbassadorDraft } from '../types/fulfilment';
export function AmbassadorDetailPage(){const {ambassadorId}=useParams();const {data,loading,error}=useFulfilment();const {data:operations,loading:operationsLoading}=useOperationsState();const [editing,setEditing]=useState(false);const ambassador=data.ambassadors.find(item=>item.ambassadorId===ambassadorId);if(loading||operationsLoading)return <main className="admin-main"><div className="repository-state panel-state">Loading ambassador file…</div></main>;if(error)return <main className="admin-main"><div className="admin-notice is-error" role="alert">{error}</div></main>;if(!ambassador)return <main className="admin-main"><p className="eyebrow">AMBASSADOR FILE</p><h1>Ambassador not found</h1><Link className="back-link" to="/ambassadors">← Return to ambassadors</Link></main>;const assignments=operations.filter(operation=>operation.ambassador===ambassador.ambassadorId).map(operation=>({operationId:operation.operationId,status:operation.operationStatus,packageName:operation.packageType,createdAt:operation.createdAt}));const save=async(draft:AmbassadorDraft)=>{await adminFulfilmentCommands.saveAmbassador(draft);setEditing(false)};return <main className="admin-main directory-detail-page"><Link className="back-link" to="/ambassadors">← Back to ambassadors</Link><header className="operation-detail-header"><div><p className="eyebrow">AMBASSADOR FILE</p><h1>{ambassador.displayName}</h1><p>{ambassador.ambassadorId}</p></div><button type="button" className="admin-button" onClick={()=>setEditing(true)}>Edit ambassador</button></header><section className="operation-section"><p className="eyebrow">OPERATIONAL PROFILE</p><h2>Roster Details</h2><dl className="operation-fields"><div className="operation-field"><dt>Phone</dt><dd>{ambassador.phone??'—'}</dd></div><div className="operation-field"><dt>Email</dt><dd>{ambassador.email??'—'}</dd></div><div className="operation-field"><dt>Status</dt><dd>{ambassador.active?'Active':'Inactive'}</dd></div><div className="operation-field"><dt>Availability</dt><dd>{ambassador.availability}</dd></div><div className="operation-field"><dt>Service campuses</dt><dd>{ambassador.campusCodes.length?ambassador.campusCodes.join(', ').toUpperCase():'All active campuses'}</dd></div></dl></section><section className="operation-section directory-related"><p className="eyebrow">ASSIGNMENT HISTORY</p><h2>Related Operations</h2><DirectoryOperationList operations={assignments}/></section>{editing&&<AmbassadorDialog record={ambassador} campuses={data.campuses} onCancel={()=>setEditing(false)} onSave={save}/>}</main>}
