import { useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import { CampusDialog } from '../components/CampusDialog';
import { DirectoryOperationList } from '../components/DirectoryOperationList';
import { adminFulfilmentCommands } from '../data/adminFulfilmentCommands';
import { useFulfilment } from '../hooks/useFulfilment';
import { useOperationsState } from '../hooks/useOperations';
import type { CampusDraft } from '../types/fulfilment';
const normalize=(value:string)=>value.trim().toLocaleLowerCase('en-ZA').replace(/\s+/g,'-');
export function CampusDetailPage(){const {campusId}=useParams();const {data,loading,error}=useFulfilment();const {data:operations,loading:operationsLoading}=useOperationsState();const [editing,setEditing]=useState(false);const campus=data.campuses.find(item=>item.campusId===campusId);if(loading||operationsLoading)return <main className="admin-main"><div className="repository-state panel-state">Loading campus file…</div></main>;if(error)return <main className="admin-main"><div className="admin-notice is-error" role="alert">{error}</div></main>;if(!campus)return <main className="admin-main"><p className="eyebrow">CAMPUS FILE</p><h1>Campus not found</h1><Link className="back-link" to="/campuses">← Return to campuses</Link></main>;const related=operations.filter(operation=>normalize(operation.campus)===campus.code||operation.campus.toLocaleLowerCase('en-ZA')===campus.name.toLocaleLowerCase('en-ZA')).map(operation=>({operationId:operation.operationId,status:operation.operationStatus,packageName:operation.packageType,createdAt:operation.createdAt}));const save=async(draft:CampusDraft)=>{await adminFulfilmentCommands.saveCampus(draft);setEditing(false)};return <main className="admin-main directory-detail-page"><Link className="back-link" to="/campuses">← Back to campuses</Link><header className="operation-detail-header"><div><p className="eyebrow">CAMPUS FILE</p><h1>{campus.name}</h1><p>{campus.code}</p></div><button type="button" className="admin-button" onClick={()=>setEditing(true)}>Edit campus</button></header><section className="operation-section"><p className="eyebrow">SERVICE PROFILE</p><h2>Campus Details</h2><dl className="operation-fields"><div className="operation-field"><dt>Stable code</dt><dd>{campus.code}</dd></div><div className="operation-field"><dt>City</dt><dd>{campus.city}</dd></div><div className="operation-field"><dt>Status</dt><dd>{campus.active?'Active':'Inactive'}</dd></div><div className="operation-field"><dt>Display order</dt><dd>{campus.displayOrder}</dd></div><div className="operation-field"><dt>Service notes</dt><dd>{campus.serviceNotes??'—'}</dd></div></dl></section><section className="operation-section directory-related"><p className="eyebrow">HISTORICAL OPERATIONS</p><h2>Related Operations</h2><DirectoryOperationList operations={related}/></section>{editing&&<CampusDialog record={campus} onCancel={()=>setEditing(false)} onSave={save}/>}</main>}
