import { useEffect,useMemo,useState,type FormEvent } from 'react';
import { PageHeader } from '../components/PageHeader';
import { adminSettingsCommands } from '../data/settingsCommands';
import { useSettings } from '../hooks/useSettings';
import type { OperationalSettingsDraft } from '../types/settings';
import '../styles/settings.css';

const draftFrom=(value:OperationalSettingsDraft):OperationalSettingsDraft=>({...value,deliveryWindows:[...value.deliveryWindows]});
const validate=(draft:OperationalSettingsDraft)=>{if(!Number.isInteger(draft.minimumLeadTimeDays)||draft.minimumLeadTimeDays<0||draft.minimumLeadTimeDays>30)return'Minimum lead time must be a whole number between 0 and 30.';if(!Number.isInteger(draft.maximumFutureDays)||draft.maximumFutureDays<1||draft.maximumFutureDays>365)return'Maximum future horizon must be a whole number between 1 and 365.';if(draft.maximumFutureDays<=draft.minimumLeadTimeDays)return'Maximum future horizon must be greater than minimum lead time.';if(!draft.deliveryWindows.length||draft.deliveryWindows.length>12)return'Provide between 1 and 12 delivery windows.';if(draft.deliveryWindows.some(item=>!item.trim()||item.trim().length>80))return'Each delivery window must contain between 1 and 80 characters.';if(new Set(draft.deliveryWindows.map(item=>item.trim())).size!==draft.deliveryWindows.length)return'Delivery windows must be unique.';if(draft.availabilityMessage.trim().length>280)return'Availability message cannot exceed 280 characters.';return''};

export function SettingsPage(){
  const {data,loading,error,refresh}=useSettings();const [form,setForm]=useState<OperationalSettingsDraft|null>(null);const [baseline,setBaseline]=useState<OperationalSettingsDraft|null>(null);const [saving,setSaving]=useState(false);const [notice,setNotice]=useState('');const [saveError,setSaveError]=useState('');
  useEffect(()=>{if(data){const next=draftFrom(data);setForm(next);setBaseline(draftFrom(next))}},[data]);
  const dirty=useMemo(()=>Boolean(form&&baseline&&JSON.stringify(form)!==JSON.stringify(baseline)),[baseline,form]);
  const update=<Key extends keyof OperationalSettingsDraft>(key:Key,value:OperationalSettingsDraft[Key])=>setForm(current=>current?{...current,[key]:value}:current);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!form||saving||!dirty)return;const validation=validate(form);if(validation){setSaveError(validation);setNotice('');return}setSaving(true);setSaveError('');setNotice('');try{const normalized={...form,availabilityMessage:form.availabilityMessage.trim(),deliveryWindows:form.deliveryWindows.map(item=>item.trim())};await adminSettingsCommands.save(normalized);setForm(draftFrom(normalized));setBaseline(draftFrom(normalized));setNotice('Operational settings saved. Customer guidance and trusted creation rules now use the updated configuration.')}catch(issue){setSaveError(issue instanceof Error?issue.message:'Operational settings could not be saved.')}finally{setSaving(false)}};
  return <main className="admin-main"><PageHeader eyebrow="SYSTEM CONTROL" title="Settings" description="Manage the operational configuration consumed by customer operation scheduling and trusted creation." />
    {error&&<div className="admin-notice is-error settings-retry" role="alert"><span>{error}</span><button type="button" onClick={refresh}>Retry settings</button></div>}
    {loading&&<div className="repository-state panel-state" aria-live="polite">Loading operational settings…</div>}
    {!loading&&form&&<form className="settings-form" onSubmit={event=>void submit(event)}>
      {notice&&<div className="admin-notice is-success" role="status">{notice}</div>}{saveError&&<div className="admin-notice is-error" role="alert">{saveError}</div>}
      <section className="operation-section settings-section"><p className="eyebrow">OPERATIONS</p><h2>Creation Availability</h2><label className="settings-toggle"><input type="checkbox" checked={form.operationCreationEnabled} onChange={event=>update('operationCreationEnabled',event.target.checked)} disabled={saving}/><span><strong>Allow new customer operations</strong><small>When disabled, customers retain access to existing files but cannot submit new operations.</small></span></label><label htmlFor="availability-message">Customer availability message</label><textarea id="availability-message" rows={3} maxLength={280} value={form.availabilityMessage} onChange={event=>update('availabilityMessage',event.target.value)} disabled={saving} placeholder="Optional message shown when operation creation is unavailable"/><small className="settings-count">{form.availabilityMessage.length}/280 characters</small></section>
      <section className="operation-section settings-section"><p className="eyebrow">DELIVERY</p><h2>Scheduling Rules</h2><div className="settings-grid"><label htmlFor="minimum-lead-time">Minimum lead time (days)<input id="minimum-lead-time" type="number" min={0} max={30} step={1} value={form.minimumLeadTimeDays} onChange={event=>update('minimumLeadTimeDays',Number(event.target.value))} disabled={saving}/><small>Zero permits same-day requests. The backend calculates this from Johannesburg's current date.</small></label><label htmlFor="maximum-future-days">Maximum future horizon (days)<input id="maximum-future-days" type="number" min={1} max={365} step={1} value={form.maximumFutureDays} onChange={event=>update('maximumFutureDays',Number(event.target.value))} disabled={saving}/><small>Must be greater than the minimum lead time.</small></label></div><label htmlFor="delivery-windows">Allowed delivery windows<textarea id="delivery-windows" rows={6} value={form.deliveryWindows.join('\n')} onChange={event=>update('deliveryWindows',event.target.value.split('\n'))} disabled={saving}/><small>Enter one customer-selectable window per line, up to 12 windows.</small></label></section>
      <footer className="settings-save-bar"><div><strong>{dirty?'Unsaved operational changes':'Configuration is up to date'}</strong><span>{data?.updatedAt?`Last updated ${new Date(data.updatedAt).toLocaleString('en-ZA')}${data.updatedBy?` by ${data.updatedBy}`:''}`:'Using centralized defaults until the first save.'}</span></div><button type="submit" className="button button--primary" disabled={!dirty||saving}>{saving?'Saving settings…':'Save Settings'}</button></footer>
    </form>}
  </main>;
}
