import { useEffect, useRef, useState } from 'react';
import type { WorkflowAction } from '../domain/operationWorkflow';
import { mockAmbassadors } from '../data/mockAmbassadors';

export function OperationActionDialog({ action, operationId, onCancel, onConfirm }: { action: WorkflowAction; operationId: string; onCancel: () => void; onConfirm: (value: { note?: string; ambassador?: string; reviewConfirmed?: boolean }) => void }) {
  const [note, setNote] = useState('');
  const [ambassador, setAmbassador] = useState('');
  const [reviewConfirmed, setReviewConfirmed] = useState(false);
  const [error, setError] = useState('');
  const back = useRef<HTMLButtonElement>(null);
  useEffect(() => { back.current?.focus(); const key = (event: KeyboardEvent) => event.key === 'Escape' && onCancel(); document.addEventListener('keydown', key); return () => document.removeEventListener('keydown', key); }, [onCancel]);
  const submit = () => { if (action.form === 'reason' && !note.trim()) return setError('Provide a reason.'); if (action.form === 'ambassador' && !ambassador) return setError('Select an ambassador.'); if (action.form === 'retry-review' && !reviewConfirmed) return setError('Confirm the review.'); onConfirm({ note: note.trim() || undefined, ambassador: ambassador || undefined, reviewConfirmed }); };
  return <div className="workflow-dialog-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onCancel()}><section role="dialog" aria-modal="true" aria-labelledby="action-title" className="workflow-dialog"><div className="workflow-dialog__heading"><span className="eyebrow">OPERATION {operationId}</span><h2 id="action-title">{action.label}</h2><p>Confirm this trusted workflow transition. An activity entry will be recorded.</p></div>{action.form === 'reason' && <div className="workflow-dialog__fields"><label htmlFor="workflow-note">Reason</label><textarea id="workflow-note" rows={4} value={note} onChange={(event) => setNote(event.target.value)} /></div>}{action.form === 'ambassador' && <div className="workflow-dialog__fields"><label htmlFor="workflow-ambassador">Available ambassador</label><select id="workflow-ambassador" value={ambassador} onChange={(event) => setAmbassador(event.target.value)}><option value="">Select an ambassador</option>{mockAmbassadors.map((item) => <option key={item.id} value={item.name}>{item.name} — {item.campus}</option>)}</select></div>}{action.form === 'retry-review' && <label className="workflow-dialog__check"><input type="checkbox" checked={reviewConfirmed} onChange={(event) => setReviewConfirmed(event.target.checked)} />Delivery details have been reviewed.</label>}{error && <p role="alert" className="workflow-dialog__error">{error}</p>}<div className="workflow-dialog__actions"><button ref={back} type="button" className="button button--secondary" onClick={onCancel}>Back</button><button type="button" className={`button ${action.tone === 'danger' ? 'button--danger' : 'button--primary'}`} onClick={submit}>Confirm {action.label.toLowerCase()}</button></div></section></div>;
}
