import { useEffect, useRef, useState } from 'react';
import type { WorkflowAction } from '../domain/operationWorkflow';
import { eligibleAmbassadors } from '../domain/ambassadorEligibility';
import { AmbassadorAssignmentState } from './AmbassadorAssignmentState';
import { useFulfilment } from '../hooks/useFulfilment';

export function OperationActionDialog({ action, operationId, campus, campusCode, onCancel, onConfirm }: { action: WorkflowAction; operationId: string; campus: string; campusCode?: string; onCancel: () => void; onConfirm: (value: { note?: string; ambassador?: string; reviewConfirmed?: boolean }) => Promise<void> }) {
  const [note, setNote] = useState('');
  const [ambassador, setAmbassador] = useState('');
  const [reviewConfirmed, setReviewConfirmed] = useState(false);
  const [error, setError] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const { data: fulfilment, loading: rosterLoading, error: rosterError } = useFulfilment();
  const availableAmbassadors = eligibleAmbassadors(fulfilment.ambassadors, { campus, campusCode });
  const selectionValid = !rosterLoading && !rosterError && availableAmbassadors.some(item => item.ambassadorId === ambassador);
  const back = useRef<HTMLButtonElement>(null);
  useEffect(() => { back.current?.focus(); const key = (event: KeyboardEvent) => event.key === 'Escape' && onCancel(); document.addEventListener('keydown', key); return () => document.removeEventListener('keydown', key); }, [onCancel]);
  const submit = async () => { if (submitting) return; if (action.form === 'reason' && !note.trim()) return setError('Provide a reason.'); if (action.form === 'ambassador' && !selectionValid) return setError('Select an ambassador.'); if (action.form === 'retry-review' && !reviewConfirmed) return setError('Confirm the review.'); setSubmitting(true);setError('');try{await onConfirm({ note: note.trim() || undefined, ambassador: ambassador || undefined, reviewConfirmed })}catch(issue){setError(issue instanceof Error?issue.message:'The operation could not be updated.')}finally{setSubmitting(false)} };
  return <div className="workflow-dialog-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && !submitting && onCancel()}><section role="dialog" aria-modal="true" aria-labelledby="action-title" className="workflow-dialog"><div className="workflow-dialog__heading"><span className="eyebrow">OPERATION {operationId}</span><h2 id="action-title">{action.label}</h2><p>Confirm this trusted workflow transition. An activity entry will be recorded.</p></div>{action.form === 'reason' && <div className="workflow-dialog__fields"><label htmlFor="workflow-note">Reason</label><textarea id="workflow-note" rows={4} value={note} onChange={(event) => setNote(event.target.value)} disabled={submitting} /></div>}{action.form === 'ambassador' && <div className="workflow-dialog__fields"><label htmlFor="workflow-ambassador">Available ambassador</label><select id="workflow-ambassador" value={ambassador} onChange={(event) => setAmbassador(event.target.value)} disabled={submitting || rosterLoading || Boolean(rosterError) || availableAmbassadors.length === 0}><option value="">Select an ambassador</option>{availableAmbassadors.map((item) => <option key={item.ambassadorId} value={item.ambassadorId}>{item.displayName} — {item.campusCodes.length ? item.campusCodes.join(', ').toUpperCase() : 'All campuses'}</option>)}</select><AmbassadorAssignmentState loading={rosterLoading} error={rosterError} total={fulfilment.ambassadors.length} eligible={availableAmbassadors.length} /></div>}{action.form === 'retry-review' && <label className="workflow-dialog__check"><input type="checkbox" checked={reviewConfirmed} onChange={(event) => setReviewConfirmed(event.target.checked)} disabled={submitting} />Delivery details have been reviewed.</label>}{error && <p role="alert" className="workflow-dialog__error">{error}</p>}<div className="workflow-dialog__actions"><button ref={back} type="button" className="button button--secondary" onClick={onCancel} disabled={submitting}>Back</button><button type="button" className={`button ${action.tone === 'danger' ? 'button--danger' : 'button--primary'}`} onClick={()=>void submit()} disabled={submitting || (action.form === 'ambassador' && !selectionValid)}>{submitting?'Updating…':`Confirm ${action.label.toLowerCase()}`}</button></div></section></div>;
}
