import { useEffect,useRef,useState,type FormEvent } from 'react';
import type { AdminPackage,PackageDraft } from '../types/packages';

export function PackageDialog({packageRecord,onCancel,onSave}:{packageRecord?:AdminPackage;onCancel:()=>void;onSave:(draft:PackageDraft)=>Promise<void>}){
 const [code,setCode]=useState(packageRecord?.code??'');const [name,setName]=useState(packageRecord?.name??'');const [shortDescription,setShortDescription]=useState(packageRecord?.shortDescription??'');const [description,setDescription]=useState(packageRecord?.description??'');const [price,setPrice]=useState(packageRecord?(packageRecord.priceMinor/100).toFixed(2):'');const [displayOrder,setDisplayOrder]=useState(String(packageRecord?.displayOrder??0));const [active,setActive]=useState(packageRecord?.active??true);const [error,setError]=useState('');const [submitting,setSubmitting]=useState(false);const cancelRef=useRef<HTMLButtonElement>(null);
 useEffect(()=>{cancelRef.current?.focus();const key=(event:KeyboardEvent)=>event.key==='Escape'&&!submitting&&onCancel();document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[onCancel,submitting]);
 const submit=async(event:FormEvent)=>{event.preventDefault();const amount=Number(price);const order=Number(displayOrder);if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(code))return setError('Use lowercase letters, numbers, and single hyphens for the stable code.');if(!name.trim()||!shortDescription.trim())return setError('Name and short description are required.');if(!Number.isFinite(amount)||amount<0)return setError('Enter a valid non-negative price.');if(!Number.isInteger(order)||order<0)return setError('Display order must be a non-negative whole number.');setSubmitting(true);setError('');try{await onSave({...(packageRecord?{packageId:packageRecord.packageId}:{}),code,name:name.trim(),shortDescription:shortDescription.trim(),...(description.trim()?{description:description.trim()}:{}),priceMinor:Math.round(amount*100),active,displayOrder:order})}catch(issue){setError(issue instanceof Error?issue.message:'The package could not be saved.')}finally{setSubmitting(false)}};
 return <div className="workflow-dialog-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&!submitting&&onCancel()}><section className="workflow-dialog package-dialog" role="dialog" aria-modal="true" aria-labelledby="package-dialog-title"><div className="workflow-dialog__heading"><span className="eyebrow">PACKAGE CATALOGUE</span><h2 id="package-dialog-title">{packageRecord?'Edit Package':'Create Package'}</h2><p>Catalogue changes affect future operations only. Existing operation snapshots remain unchanged.</p></div><form onSubmit={event=>void submit(event)}><div className="workflow-dialog__fields package-dialog__fields"><label htmlFor="package-code">Stable code</label><input id="package-code" value={code} onChange={event=>setCode(event.target.value)} disabled={Boolean(packageRecord)} required/><label htmlFor="package-name">Name</label><input id="package-name" value={name} onChange={event=>setName(event.target.value)} required/><label htmlFor="package-short">Short description</label><textarea id="package-short" rows={2} value={shortDescription} onChange={event=>setShortDescription(event.target.value)} required/><label htmlFor="package-description">Long description (optional)</label><textarea id="package-description" rows={4} value={description} onChange={event=>setDescription(event.target.value)}/><div className="package-dialog__row"><label htmlFor="package-price">Price (ZAR)<input id="package-price" type="number" min="0" step="0.01" inputMode="decimal" value={price} onChange={event=>setPrice(event.target.value)} required/></label><label htmlFor="package-order">Display order<input id="package-order" type="number" min="0" step="1" value={displayOrder} onChange={event=>setDisplayOrder(event.target.value)} required/></label></div><label className="workflow-dialog__check"><input type="checkbox" checked={active} onChange={event=>setActive(event.target.checked)}/><span><strong>{active?'Active':'Inactive'}</strong><br/>Inactive packages remain historically available but cannot be selected for new operations.</span></label></div>{error&&<p className="workflow-dialog__error" role="alert">{error}</p>}<div className="workflow-dialog__actions"><button ref={cancelRef} type="button" className="button button--secondary" onClick={onCancel} disabled={submitting}>Back</button><button type="submit" className="button button--primary" disabled={submitting}>{submitting?'Saving…':packageRecord?'Save changes':'Create package'}</button></div></form></section></div>;
}
