import type { Timestamp } from 'firebase/firestore';
export type InternalOperationStatus='NEW'|'PAYMENT_PENDING'|'PAID'|'REVIEW_REQUIRED'|'APPROVED'|'PREPARING'|'READY_FOR_DELIVERY'|'AMBASSADOR_ASSIGNED'|'OUT_FOR_DELIVERY'|'DELIVERED'|'COMPLETED'|'REJECTED'|'CANCELLED'|'DELIVERY_FAILED'|'REFUNDED';
export type CustomerProjectionStatus='PAYMENT_PENDING'|'CONFIRMED'|'PREPARING'|'DELIVERY_SCHEDULED'|'IN_PROGRESS'|'DELIVERED'|'COMPLETE'|'REQUIRES_ATTENTION'|'CANCELLED'|'DELIVERY_ISSUE'|'REFUNDED';
export interface OperationDocument { operationId:string;customerId:string;package:{packageId:string;nameSnapshot:string;priceMinor:number;currency:'ZAR'};status:InternalOperationStatus;recipient:{name:string;phone:string;campus:string;campusCode?:string;residence:string;deliveryLocation:string;deliveryInstructions?:string};delivery:{requestedDate:string;requestedWindow:string;scheduledDeliveryAt?:Timestamp;assignedAmbassadorId?:string;deliveredAt?:Timestamp};anonymousMessage:string;paymentSummary:{status:'PENDING'|'PAID'|'REFUNDED'|'FAILED';amountMinor:number;currency:'ZAR';paidAt?:Timestamp};createdAt:Timestamp;updatedAt:Timestamp }
export interface OperationInternalDocument { operationId:string;moderation:{status:'PENDING'|'APPROVED'|'REJECTED';reviewedBy?:string;reviewedAt?:Timestamp;reasonCode?:string;reasonNote?:string};delivery:{failureReasonCode?:string;failureDetails?:string;retryCount:number;internalNotes?:string;ambassadorPhone?:string};staffNotes?:string;safetyFlags:string[];updatedAt:Timestamp }
export interface CustomerOperationDocument { operationId:string;customerId:string;package:{name:string;amountMinor:number;currency:'ZAR'};status:CustomerProjectionStatus;recipient:{name:string;campus:string;residence:string};delivery:{requestedDate:string;requestedWindow:string;location:string;deliveredAt?:Timestamp};anonymousMessage:string;paymentSummary:{status:'PENDING'|'PAID'|'REFUNDED';amountMinor:number;currency:'ZAR'};tracking:{status:CustomerProjectionStatus;updatedAt:Timestamp};createdAt:Timestamp;updatedAt:Timestamp;archived?:boolean;archivedAt?:Timestamp }
export interface OperationActivityDocument { operationId:string;type:string;timestamp:Timestamp;actorId:string;actorRole:'ADMIN'|'CUSTOMER'|'AMBASSADOR'|'SYSTEM';fromStatus?:InternalOperationStatus;toStatus?:InternalOperationStatus;reasonCode?:string;note?:string }
export interface PackageDocument { packageId:string;code:string;name:string;shortDescription:string;description?:string;priceMinor:number;currency:'ZAR';active:boolean;displayOrder:number;createdAt:Timestamp;updatedAt:Timestamp }
export interface AmbassadorDocument { ambassadorId:string;displayName:string;phone?:string;email?:string;campusCodes:string[];active:boolean;availability:'AVAILABLE'|'UNAVAILABLE';createdAt:Timestamp;updatedAt:Timestamp }
export interface CampusDocument { campusId:string;code:string;name:string;city:string;active:boolean;serviceNotes?:string;displayOrder:number;createdAt:Timestamp;updatedAt:Timestamp }
