import { Timestamp } from 'firebase-admin/firestore';
import { HttpsError } from 'firebase-functions/v2/https';
import { getAdminFirestore } from '../firebaseAdmin.js';
import type { OperationRecord,PaymentRecord } from '../domain/operationTypes.js';
import { validateTransition } from '../domain/operationWorkflow.js';
import { buildCustomerOperationProjection,customerArchiveMetadataFrom } from '../projection/customerOperationProjection.js';
export interface ConfirmedProviderPayment {paymentId:string;providerPaymentId:string;amountMinor:number;currency:'ZAR'}
/** Called only after a Yoco webhook adapter has verified authenticity. */
export const confirmOperationPayment=async(event:ConfirmedProviderPayment):Promise<'CONFIRMED'|'ALREADY_CONFIRMED'>=>{const db=getAdminFirestore();const paymentRef=db.collection('payments').doc(event.paymentId);const activityRef=db.collection('operationActivity').doc();return db.runTransaction(async transaction=>{const paymentSnapshot=await transaction.get(paymentRef);if(!paymentSnapshot.exists)throw new HttpsError('not-found','Payment record not found.');const payment=paymentSnapshot.data() as PaymentRecord;if(payment.provider!=='YOCO'||payment.amountMinor!==event.amountMinor||payment.currency!==event.currency)throw new HttpsError('failed-precondition','Provider payment does not match the authoritative payment record.');if(payment.status==='PAID')return'ALREADY_CONFIRMED';if(payment.status!=='PENDING')throw new HttpsError('failed-precondition','Payment is not awaiting confirmation.');const operationRef=db.collection('operations').doc(payment.operationId);const projectionRef=db.collection('customerOperations').doc(payment.operationId);const [operationSnapshot,projectionSnapshot]=await Promise.all([transaction.get(operationRef),transaction.get(projectionRef)]);if(!operationSnapshot.exists)throw new HttpsError('not-found','Operation not found.');const operation=operationSnapshot.data() as OperationRecord;if(operation.customerId!==payment.customerId||operation.package.priceMinor!==payment.amountMinor||operation.package.currency!==payment.currency)throw new HttpsError('failed-precondition','Payment ownership or amount does not match the operation snapshot.');validateTransition(operation.status,'PAID',{});const now=Timestamp.now();const next:OperationRecord={...operation,status:'PAID',paymentSummary:{...operation.paymentSummary,status:'PAID',paidAt:now},updatedAt:now};const nextPayment:PaymentRecord={...payment,status:'PAID',providerPaymentId:event.providerPaymentId,paidAt:now,updatedAt:now};transaction.set(paymentRef,nextPayment);transaction.update(operationRef,{status:'PAID',paymentSummary:next.paymentSummary,updatedAt:now});transaction.set(projectionRef,buildCustomerOperationProjection(next,customerArchiveMetadataFrom(projectionSnapshot.data())));transaction.create(activityRef,{operationId:operation.operationId,type:'PAYMENT_CONFIRMED',timestamp:now,actorId:'yoco-webhook',actorRole:'SYSTEM',fromStatus:operation.status,toStatus:'PAID',note:'Trusted payment confirmation received.'});return'CONFIRMED'})};
