import { Timestamp } from 'firebase-admin/firestore';
import { HttpsError, onCall } from 'firebase-functions/v2/https';
import { requireAdmin } from '../auth/requireAdmin.js';
import type { AmbassadorRecord } from '../domain/operationTypes.js';
import { getAdminFirestore } from '../firebaseAdmin.js';

interface Input { ambassadorId?:string;displayName:string;phone?:string;email?:string;campusCodes:string[];active:boolean;availability:'AVAILABLE'|'UNAVAILABLE' }
const required=(value:unknown,label:string,max:number)=>{if(typeof value!=='string'||!value.trim())throw new HttpsError('invalid-argument',`${label} is required.`);const result=value.trim();if(result.length>max)throw new HttpsError('invalid-argument',`${label} is too long.`);return result};
const optional=(value:unknown,label:string,max:number)=>typeof value==='string'&&value.trim()?required(value,label,max):undefined;
const parse=(value:unknown):Input=>{if(typeof value!=='object'||value===null)throw new HttpsError('invalid-argument','Ambassador data is required.');const input=value as Record<string,unknown>;if(!Array.isArray(input.campusCodes)||input.campusCodes.some(code=>typeof code!=='string'||!code.trim()))throw new HttpsError('invalid-argument','Service campuses are invalid.');if(typeof input.active!=='boolean'||!['AVAILABLE','UNAVAILABLE'].includes(String(input.availability)))throw new HttpsError('invalid-argument','Operational state is invalid.');return{...(typeof input.ambassadorId==='string'&&input.ambassadorId.trim()?{ambassadorId:input.ambassadorId.trim()}:{}),displayName:required(input.displayName,'Display name',120),...(optional(input.phone,'Phone',40)?{phone:optional(input.phone,'Phone',40)}:{}),...(optional(input.email,'Email',240)?{email:optional(input.email,'Email',240)}:{}),campusCodes:[...new Set(input.campusCodes.map(code=>String(code).trim().toLowerCase()))],active:input.active,availability:input.availability as Input['availability']}};

export const saveAmbassador=onCall<unknown>(async request=>{requireAdmin(request);const input=parse(request.data);const db=getAdminFirestore();const now=Timestamp.now();const ref=input.ambassadorId?db.collection('ambassadors').doc(input.ambassadorId):db.collection('ambassadors').doc();await db.runTransaction(async transaction=>{const snapshot=await transaction.get(ref);if(input.ambassadorId&&!snapshot.exists)throw new HttpsError('not-found','Ambassador no longer exists.');const existing=snapshot.exists?snapshot.data() as AmbassadorRecord:undefined;const record:AmbassadorRecord={ambassadorId:ref.id,displayName:input.displayName,...(input.phone?{phone:input.phone}:{}),...(input.email?{email:input.email}:{}),campusCodes:input.campusCodes,active:input.active,availability:input.availability,createdAt:existing?.createdAt??now,updatedAt:now};transaction.set(ref,record)});return{ambassadorId:ref.id}});
