import { useState } from 'react';
import { useAssignments } from '../hooks/useAssignments';
import { DeliveryCard } from '../components/DeliveryCard';
import { LoadState } from '../components/LoadState';

export function OperationsPage() {
  const [count, setCount] = useState(50), [search, setSearch] = useState(''), [filter, setFilter] = useState('ALL');
  const { items, loading, error, retry } = useAssignments(undefined, count);
  const query = search.trim().toLocaleLowerCase('en-ZA');
  const visible = items.filter(item => (filter === 'ALL' || (filter === 'ACTIVE' ? ['AMBASSADOR_ASSIGNED', 'OUT_FOR_DELIVERY'].includes(item.status) : filter === 'DONE' ? ['DELIVERED', 'COMPLETED'].includes(item.status) : item.status === filter)) && (!query || [item.operationId, item.recipient.name, item.recipient.campus, item.recipient.residence].some(value => value.toLocaleLowerCase('en-ZA').includes(query))));
  return <main id="main" className="portal-main"><header className="page-header"><span className="eyebrow">ASSIGNED FILES</span><h1>My Deliveries</h1><p>Only operations currently assigned to your account are accessible here, including retained delivery history.</p></header><section className="filters" aria-label="Delivery filters"><label>Search<input type="search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Reference, recipient, campus or residence" /></label><label>Status<select value={filter} onChange={event => setFilter(event.target.value)}><option value="ALL">All</option><option value="ACTIVE">Active</option><option value="AMBASSADOR_ASSIGNED">Assigned / Upcoming</option><option value="OUT_FOR_DELIVERY">Out for Delivery</option><option value="DONE">Delivered / Completed</option><option value="DELIVERY_FAILED">Issues</option></select></label></section>{loading || error ? <LoadState loading={loading} error={error} retry={retry} /> : <><p className="muted" role="status">{visible.length} matches in {items.length} loaded assignments.</p>{visible.length ? <div className="card-grid">{visible.map(item => <DeliveryCard key={item.operationId} operation={item} />)}</div> : <div className="panel"><h2>{items.length ? 'No matching deliveries' : 'No assignments yet'}</h2><p>{items.length ? 'Try another search or clear the filters.' : 'Admin assignments will appear here automatically once your account is linked.'}</p>{items.length > 0 && <button onClick={() => { setSearch(''); setFilter('ALL'); }}>Clear filters</button>}</div>}{items.length >= count && count < 200 && <button className="load-more" onClick={() => setCount(value => Math.min(200, value + 50))}>Load more history</button>}{count === 200 && items.length >= 200 && <p className="notice">Showing the latest 200 assignments. Contact Admin for older records.</p>}</>}</main>;
}
