import { useState,type FormEvent,type KeyboardEvent } from 'react';
import { Link,useNavigate } from 'react-router-dom';
import { customerOperationCommands } from '../data/customerOperationCommands';
import { useCustomerCatalog } from '../hooks/useCustomerCatalog';
import type { CreateCustomerOperationInput } from '../types/operationCreation';

interface FormState {packageId:string;recipientName:string;recipientPhone:string;campus:string;residence:string;deliveryLocation:string;deliveryInstructions:string;anonymousMessage:string;requestedDate:string;requestedWindow:string}
const initialForm:FormState={packageId:'',recipientName:'',recipientPhone:'',campus:'',residence:'',deliveryLocation:'',deliveryInstructions:'',anonymousMessage:'',requestedDate:'',requestedWindow:''};
const localToday=()=>{const now=new Date();return`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`};
const addDateOnlyDays=(value:string,days:number)=>{const result=new Date(Date.UTC(Number(value.slice(0,4)),Number(value.slice(5,7))-1,Number(value.slice(8,10))+days));return`${result.getUTCFullYear()}-${String(result.getUTCMonth()+1).padStart(2,'0')}-${String(result.getUTCDate()).padStart(2,'0')}`};
const validate=(form:FormState,minimumDate:string,maximumDate:string,windows:readonly string[])=>{if(!form.packageId)return'Select an operation package.';if(!form.recipientName.trim())return'Enter the recipient name.';if(!form.recipientPhone.trim())return'Enter a recipient contact number.';if(!form.campus)return'Select a supported campus.';if(!form.residence.trim())return'Enter the residence or building.';if(!form.deliveryLocation.trim())return'Enter a precise delivery location.';if(!form.anonymousMessage.trim())return'Enter the anonymous message.';if(!form.requestedDate)return'Select a requested delivery date.';if(form.requestedDate<minimumDate)return`Select a date on or after ${minimumDate}.`;if(form.requestedDate>maximumDate)return`Select a date on or before ${maximumDate}.`;if(!windows.includes(form.requestedWindow))return'Select an available delivery window.';return null};

export function CustomerNewOperationPage(){
  const [form,setForm]=useState<FormState>(initialForm);const [submitting,setSubmitting]=useState(false);const [error,setError]=useState<string|null>(null);const navigate=useNavigate();const {data:catalog,loading:catalogLoading,error:catalogError,refresh}=useCustomerCatalog();const selectedPackage=catalog.packages.find(item=>item.packageId===form.packageId);const update=<Key extends keyof FormState,>(key:Key,value:FormState[Key])=>setForm(current=>({...current,[key]:value}));const minimumDate=addDateOnlyDays(localToday(),catalog.settings.minimumLeadTimeDays);const maximumDate=addDateOnlyDays(localToday(),catalog.settings.maximumFutureDays);const creationDisabled=!catalog.settings.operationCreationEnabled;const unavailable=catalogLoading||Boolean(catalogError)||!catalog.packages.length||!catalog.campuses.length||creationDisabled;
  const preventDateTextEntry=(event:KeyboardEvent<HTMLInputElement>)=>{if(event.key.length===1||event.key==='Backspace'||event.key==='Delete')event.preventDefault()};
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(submitting||unavailable)return;const validationError=validate(form,minimumDate,maximumDate,catalog.settings.deliveryWindows);if(validationError){setError(validationError);return}setSubmitting(true);setError(null);const input:CreateCustomerOperationInput={packageId:form.packageId,recipient:{name:form.recipientName,phone:form.recipientPhone,campus:form.campus,residence:form.residence,deliveryLocation:form.deliveryLocation,...(form.deliveryInstructions.trim()?{deliveryInstructions:form.deliveryInstructions}:{})},delivery:{requestedDate:form.requestedDate,requestedWindow:form.requestedWindow},anonymousMessage:form.anonymousMessage};try{const result=await customerOperationCommands.createOperation(input);navigate(`/operations/${result.operationId}`,{replace:true,state:{operationCreated:true}})}catch(submissionError){setError(submissionError instanceof Error?submissionError.message:'The operation could not be submitted. Please try again.')}finally{setSubmitting(false)}};
  return <main className="client-main operation-create-page"><Link className="client-back-link" to="/operations">← My Operations</Link><header className="operation-create-header"><p className="customer-eyebrow">SECURE DIRECTIVE</p><h1>Initiate Operation</h1><p>Submit a private operation request for review by the Secret Service operations team.</p></header>{creationDisabled&&!catalogLoading&&!catalogError&&<div className="operation-availability-notice" role="status"><strong>New operations are temporarily unavailable.</strong><span>{catalog.settings.availabilityMessage||'Please return later or review your existing operation files.'}</span></div>}<form className="operation-create-form" onSubmit={event=>void submit(event)} noValidate>{error&&<div className="operation-form-error" role="alert">{error}</div>}{catalogError&&<div className="customer-load-error" role="alert"><p>{catalogError}</p><button type="button" onClick={refresh}>Try again</button></div>}
    <fieldset disabled={submitting||creationDisabled}><legend><span>01</span> Select Package</legend>{catalogLoading?<p className="customer-empty" aria-live="polite">Loading active packages…</p>:catalog.packages.length?<><label className="operation-package-select">Select Package<select value={form.packageId} onChange={event=>update('packageId',event.target.value)} required><option value="" disabled>Choose a package</option>{catalog.packages.map(item=><option key={item.packageId} value={item.packageId}>{item.name}</option>)}</select></label>{selectedPackage&&<div className="selected-package-summary" aria-live="polite"><strong>{selectedPackage.name}</strong><span>{selectedPackage.description}</span><b>R {(selectedPackage.priceMinor/100).toFixed(2)}</b></div>}</>:!catalogError&&<div className="customer-empty"><p>No active operation packages are currently available.</p></div>}</fieldset>
    <fieldset disabled={submitting||creationDisabled}><legend><span>02</span> Recipient Intelligence</legend><div className="operation-form-grid"><label>Recipient name<input value={form.recipientName} onChange={event=>update('recipientName',event.target.value)} maxLength={120} autoComplete="name" required/></label><label>Recipient phone<input type="tel" value={form.recipientPhone} onChange={event=>update('recipientPhone',event.target.value)} maxLength={40} autoComplete="tel" required/></label><label>Campus<select value={form.campus} onChange={event=>update('campus',event.target.value)} required><option value="">Select a supported campus</option>{catalog.campuses.map(campus=><option key={campus.campusId} value={campus.code}>{campus.name} · {campus.city}</option>)}</select></label><label>Residence or building<input value={form.residence} onChange={event=>update('residence',event.target.value)} maxLength={160} required/></label><label className="full-width">Delivery location<input value={form.deliveryLocation} onChange={event=>update('deliveryLocation',event.target.value)} maxLength={240} placeholder="Reception, office number, entrance or meeting point" required/></label><label className="full-width">Delivery instructions <small>Optional</small><textarea value={form.deliveryInstructions} onChange={event=>update('deliveryInstructions',event.target.value)} maxLength={1000} rows={3}/></label></div>{!catalogLoading&&!catalogError&&!catalog.campuses.length&&<div className="customer-empty"><p>No active campuses are currently accepting operations.</p></div>}</fieldset>
    <fieldset disabled={submitting||creationDisabled}><legend><span>03</span> Anonymous Message</legend><label>Message content<textarea value={form.anonymousMessage} onChange={event=>update('anonymousMessage',event.target.value)} maxLength={2000} rows={7} aria-describedby="message-guidance" required/></label><p id="message-guidance">Messages are reviewed before fulfilment. Do not include threats, harassment, or unsafe instructions.</p></fieldset>
    <fieldset disabled={submitting||creationDisabled}><legend><span>04</span> Delivery Request</legend><div className="operation-form-grid"><label>Requested date<input type="date" min={minimumDate} max={maximumDate} value={form.requestedDate} onChange={event=>update('requestedDate',event.target.value)} onKeyDown={preventDateTextEntry} onPaste={event=>event.preventDefault()} onDrop={event=>event.preventDefault()} inputMode="none" aria-describedby="requested-date-guidance" required/><small id="requested-date-guidance">Choose a date from {minimumDate} through {maximumDate} using the calendar picker.</small></label><label>Requested window<select value={form.requestedWindow} onChange={event=>update('requestedWindow',event.target.value)} required><option value="">Select an available window</option>{catalog.settings.deliveryWindows.map(window=><option key={window} value={window}>{window}</option>)}</select></label></div></fieldset>
    <section className="operation-submit-panel"><div><p className="customer-eyebrow">FINAL CHECK</p><h2>Submit for review</h2><p>The operations team securely manages review, scheduling and fulfilment.</p></div><button className="customer-primary" type="submit" disabled={submitting||unavailable}>{submitting?'Transmitting securely…':catalogLoading?'Loading catalogue…':creationDisabled?'Creation Unavailable':'Submit Operation'}</button></section>
  </form></main>;
}
