import { Link } from 'react-router-dom';
import { PublicInfoLayout } from '../components/PublicInfoLayout';

export function PrivacyPage() {
  return <PublicInfoLayout title="Privacy Policy" draft introduction="How information is used in the current Secret Service platform.">
    <section><h2>Account information</h2><p>Firebase Authentication manages customer sign-in. Account information includes your email, account identifier and any display name supplied. Your identifier connects you to your operations. Do not share your password or send it through the Contact page.</p></section>
    <section><h2>Operation and recipient information</h2><p>Requests include package details, recipient name and phone number, campus or service area, building and delivery location, instructions, message content, and requested date or window. We use this information to review, prepare and fulfil the operation. Package and location snapshots preserve the context of an existing request when catalogue records change.</p><p>Recipient information may be supplied by the sender rather than by the recipient. Provide only information needed for the request. An anonymous delivery experience does not make the sender anonymous to the platform: operations remain linked to customer accounts.</p></section>
    <section><h2>Payment information</h2><p>Payments use Yoco checkout. The platform stores operational payment information such as amount, currency, checkout or transaction references, and payment status for verification and reconciliation. Enter payment instrument details only in the provider checkout, not in messages or delivery instructions. Yoco processes checkout information under its own terms and privacy practices.</p></section>
    <section><h2>Platform services and necessary sharing</h2><p>Firebase Authentication supports accounts, Firestore stores platform records, and Firebase Functions handles trusted requests and workflow commands. Google/Firebase and Yoco process information needed to provide those services. Authorised administrators access operational records; assigned ambassadors receive the delivery information needed for their work. Customer-facing tracking excludes privileged staff notes and private ambassador contact details.</p></section>
    <section><h2>Activity, delivery and security records</h2><p>Operational history can record actions, actor references, timestamps, assignments, delivery outcomes and internal reasons. Technical logs support troubleshooting, payment verification and security. These records can contain operation or account references. Access restrictions and backend checks help protect information; this draft does not promise absolute security.</p></section>
    <section><h2>Retention and archiving</h2><p>Records are kept for operational history, payment reconciliation, security and applicable recordkeeping needs. This draft does not specify a fixed retention or deletion schedule; that schedule requires review before launch. Archiving an operation in the Customer Portal is not deletion of authoritative operational or payment records.</p></section>
    <section><h2>Questions and information requests</h2><p>Customers and recipients can use the <Link to="/contact">Contact page</Link> to ask about their information or request access, correction or deletion. Identity and the relevant records may need to be checked before a request can be addressed. This is not an automated deletion service, and some records may need to be retained. Do not send passwords or payment instrument details.</p></section>
    <section><h2>Review and updates</h2><p>This draft needs confirmation of the business's actual data practices, retention arrangements and applicable privacy obligations before launch. The policy should be updated when those practices change; its presence on the site is not a regulatory certification.</p></section>
  </PublicInfoLayout>;
}
