import { Link } from 'react-router-dom';
import { PublicInfoLayout } from '../components/PublicInfoLayout';

export function TermsPage() {
  return <PublicInfoLayout title="Terms & Conditions" draft introduction="Operational expectations for using Secret Service and requesting an operation.">
    <section><h2>Accounts and responsibility</h2><p>Use an account you are authorised to control, provide accurate information and keep your credentials private. Only submit requests you are lawfully entitled to make. Any formal eligibility requirements need confirmation before commercial launch; creating an account does not by itself establish eligibility for every request.</p></section>
    <section><h2>Requests and moderation</h2><p>Browsing or selecting a package is not an order reservation. Requests are submitted in the Customer Portal and reviewed by the team. Approval is required before the payment stage; a request may instead need attention or be rejected. Provide accurate recipient and delivery information and only the information necessary for the operation.</p></section>
    <section><h2>Pricing and payment timing</h2><p>The backend validates the active package and stores its price with your submitted operation. Later catalogue changes do not change that stored amount. Review the operation and checkout amount before paying. When the operation is Payment Required, payment uses Yoco checkout. A checkout return page alone does not establish payment: the backend must verify it before preparation proceeds.</p></section>
    <section><h2>Delivery and ambassadors</h2><p>Requested dates and windows are subject to operational review and are not guaranteed delivery times. Assigned ambassadors carry out delivery work and report outcomes through the platform. Customer tracking shows workflow progress, not a guaranteed arrival time or live location.</p></section>
    <section><h2>Prohibited misuse</h2><p>Do not use the service for threats, harassment, stalking, fraud, impersonation or unlawful content. Do not supply information you are not entitled to use, bypass access controls, or attempt to access another person's account or operations. Anonymous presentation is not permission to harm others or evade responsibility.</p></section>
    <section><h2>Failures, cancellation and refunds</h2><p>Delivery failures are reviewed by the team. A retry or cancellation depends on the operation's state and the applicable workflow. A cancelled or failed operation does not automatically trigger a refund. A displayed refund state is not a general refund guarantee or policy. Contact the team about a specific case; this draft does not restrict applicable consumer rights or establish a completed refund policy.</p></section>
    <section><h2>Service availability</h2><p>Package availability, service areas and operational capacity can change. Technical interruptions may affect access or updates. This draft offers no guaranteed uptime, completion deadline or delivery outcome. Check your operation status and contact the team if an outcome is unclear.</p></section>
    <section><h2>Site content</h2><p>Use the site content to understand and access the service. Do not misrepresent an affiliation with Secret Service or reuse branding or content in ways that infringe the rights of its owners. Submitting a message does not establish ownership of material belonging to someone else.</p></section>
    <section><h2>Changes and contact</h2><p>These draft terms need legal review and approval before commercial launch. Future terms should reflect the service actually offered and explain material changes when published. For questions about an operation or these terms, use <Link to="/contact">Contact</Link>. See the <Link to="/privacy">Privacy Policy draft</Link> for information handling.</p></section>
  </PublicInfoLayout>;
}
